name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
# name: Deploy AWS CDK
# on: [push, workflow_dispatch]

# jobs:
#   aws_cdk:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout Repo
#         uses: actions/checkout@v3

#       - name: Configure aws credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#           aws-region: 'us-east-1'

#       - name: Install Dependencies
#         run: 'npm i'
#         working-directory: ./cdk

#       - name: CDK Synth
#         run: 'cdk synth'
#         working-directory: ./cdk

#       - name: CDK Deploy 
#         run: 'cdk deploy --all --require-approval never'
#         working-directory: ./cdk
