name: Deploy AWS CDK
on: [push, workflow_dispatch]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'

      - name: Install Dependencies and Build
        run: 'npm i'
        npm: 'npm run build'
        working-directory: ./cdk

      - name: CDK Synth
        run: 'cdk synth'
        working-directory: ./cdk

      - name: CDK Deploy 
        run: 'cdk deploy --all --require-approval never'
        working-directory: ./cdk
