name: Deploy AWS CDK

# controls when these actions will rn
on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"

      - name: Configure AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm i

      # - name: cdk diff
      #   uses: youyo/aws-cdk-github-actions@v2.1.3
      #   with:
      #     cdk_subcommand: 'diff'
      #     actions_comment: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #     AWS_DEFAULT_REGION: 'us-east-1'

      - name: CDK Deploy
      - run: 'cdk deploy'
      - working_directory: 'cdk'

      - name: CDK Synth
          run: 'cdk synth'
          working_directory: 'cdk'

